---
- name: Install Apache Tomcat
  hosts: "{{ tower_webhook_payload.pull_request.base.ref | default ('dev') }}"
  
  roles:
    - role: tomcat-ansible-role
      when: tower_webhook_payload.action != 'closed'
